### ISSUE TITLE
FreeCad 0.21.2 incompatibility

### ISSUE THREAD

**Issue by dl6lr** [dl6lr/LCInterlocking#4]
Opening a file with a MultiJoin in it results in:

```
21:44:35  <string>(1)<class 'TypeError'>: __dict__ must be set to a dictionary, not a 'str'
21:44:35  <string>(1)<class 'TypeError'>: __dict__ must be set to a dictionary, not a 'str'

```
Trying to edit a MultiJoin results in this exception:

```
21:44:43  QLayout: Attempting to add QLayout "" to QWidget "TreePanel", which already has a layout
21:44:43  QLayout: Attempting to add QLayout "" to QWidget "TreePanel", which already has a layout
21:44:43  QLayout: Attempting to add QLayout "" to QWidget "TreePanel", which already has a layout
21:44:43  QLayout: Attempting to add QLayout "" to QWidget "TreePanel", which already has a layout
21:44:43  QLayout: Attempting to add QLayout "" to QWidget "TreePanel", which already has a layout
21:44:43  Traceback (most recent call last):
  File "C:\Users\laengerich\AppData\Roaming\FreeCAD\Mod\LCInterlocking\panel\multiplejoins.py", line 189, in setEdit
    FreeCADGui.Control.showDialog(MultipleJoins(self.Object))
  File "C:\Users\laengerich\AppData\Roaming\FreeCAD\Mod\LCInterlocking\panel\multiplejoins.py", line 225, in __init__
    super(MultipleJoins, self).__init__("Parts and tabs", obj_join)
  File "C:\Users\laengerich\AppData\Roaming\FreeCAD\Mod\LCInterlocking\panel\treepanel.py", line 94, in __init__
    for item in self.parts:
  File "C:\Users\laengerich\AppData\Roaming\FreeCAD\Mod\LCInterlocking\panel\propertieslist.py", line 20, in __getitem__
    return self.lst[index]
<class 'AttributeError'>: 'PropertiesList' object has no attribute 'lst'
21:59:35  PropertyPythonObject::toString(): failed for <class 'panel.multiplejoins.MultipleJoinViewProvider'>
21:59:35  Traceback (most recent call last):
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type ViewProviderDocumentObject is not JSON serializable

```

**Comment by dl6lr** [comment]
Trying to save a MultiJoin:

`17:45:58  PropertyPythonObject::toString(): failed for <class 'panel.propertieslist.PropertiesList'>
17:45:58  Traceback (most recent call last):
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type TabProperties is not JSON serializable
17:45:58  PropertyPythonObject::toString(): failed for <class 'panel.propertieslist.PropertiesList'>
17:45:58  Traceback (most recent call last):
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type MaterialProperties is not JSON serializable
17:45:58  PropertyPythonObject::toString(): failed for <class 'panel.multiplejoins.MultipleJoinViewProvider'>
17:45:58  Traceback (most recent call last):
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\compiler\PortableApps\FreeCadPortable_0.21.2\App\FreeCAD\bin\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
<class 'TypeError'>: Object of type ViewProviderDocumentObject is not JSON serializable
`

Seems this is due to JSONEncoder does not know how to deal with PropertiesList.

**Comment by dl6lr** [comment]
Thanks to the pull request by @jcma68 this seems to be solved.
